spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: Welcome01
    platform: postgres
    testWhileIdle: 'true'
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    validationQuery: SELECT 1
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: MessageApp

server:
  port: 8080

kafka:
  topic:
    boot: test
